### ISSUE TITLE
Download snagging in IE

### ISSUE THREAD

**Issue by kellyhiser** [therabble/org.spl.playback#115]
Kate on August 3 says: In IE, I get a progress notice, but no progress happens, ie it’s been this way for 10 minutes even if I go to other albums and stream other songs: 
![unnamed 1](https://cloud.githubusercontent.com/assets/8515447/17386453/febfb0a0-59b8-11e6-95c4-6c4eb445a904.jpg)

Windows 7, 64-bit, and on version 11 of IE

**Comment by prestonaustin** [comment]
Need javacript console output, and ideally network call log as well, from cases in impacted browsers. Not aware of a generic cause for this. Probably it is an error before calling the server at all, or perhaps a failure to capture response properly since it just hangs. We can possibly construct a different mechanism for linking for IE.

**Comment by kellyhiser** [comment]
Walker did some testing for us on his PC at work this morning (because he's a hero). Windows 7 (service pack 1) and IE 11:

When he logs in, the console in IE's F12 developer tools says:

SEC7118: XMLHttpRequest for https://playback-api.spl.org/auth/users/19f70d5be12f8069d08ce4aad8edde1f488ce9ef required Cross Origin Resource Sharing (CORS).
File: syrinx-effect-snail-songs
SEC7119: XMLHttpRequest for https://playback-api.spl.org/auth/users/19f70d5be12f8069d08ce4aad8edde1f488ce9ef required CORS preflight.
File: syrinx-effect-snail-songs
SEC7118: XMLHttpRequest for https://playback-api.spl.org/collection required Cross Origin Resource Sharing (CORS).
File: syrinx-effect-snail-songs
SEC7119: XMLHttpRequest for https://playback-api.spl.org/collection required CORS preflight.
File: syrinx-effect-snail-songs


When he has successfully logged in and then attempts to download a track the download fails as it did for Kate (progress bar appears but does not progress) and the console returns a red "x" and "undefined"


I kinda doubt this is helpful but the debugger displayed the following during this testing:

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/" />
<meta name="musicat/config/environment" content="%7B%22modulePrefix%22%3A%22musicat%22%2C%22environment%22%3A%22production%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22contentSecurityPolicyHeader%22%3A%22Content-Security-Policy-Report-Only%22%2C%22contentSecurityPolicy%22%3A%7B%22connect-src%22%3A%22*.spl.org%20*.musicat.co%20http%3A//localhost%3A4200%20http%3A//localhost%3A5000%20http%3A//localhost%3A7302%20https%3A//vimeo.com%20https%3A//raw.githubusercontent.com%22%2C%22script-src%22%3A%22%27self%27%20%27unsafe-inline%27%20%27unsafe-eval%27%20http%3A//www.google-analytics.com%22%2C%22font-src%22%3A%22%27self%27%22%2C%22img-src%22%3A%22%27self%27%20*.spl.org%20data%3A%20http%3A//www.google-analytics.com%20http%3A//localhost%3A7302%22%2C%22media-src%22%3A%22*.spl.org%20http%3A//localhost%3A7302%20data%3A%20%22%2C%22child-src%22%3A%22*.youtube.com%20https%3A//player.vimeo.com%22%2C%22style-src%22%3A%22%27unsafe-inline%27%20http%3A//localhost%3A4200%22%2C%22default-src%22%3A%22%27none%27%22%7D%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%22APPLICATION_NAME%22%3A%22Seattle%20PlayBack%22%2C%22APPLICATION_EMAIL%22%3A%22spl.playback@therabble.co%22%2C%22APPLICATION_LIBRARY%22%3A%22The%20Seattle%20Public%20Library%22%2C%22APPLICATION_REGION%22%3A%22Seattle%22%2C%22APIAUTH%22%3A%22697783e17f921472e39e9bd1f5fc548cfed2f123%22%2C%22API%22%3A%22https%3A//playback-api.spl.org%22%2C%22MMS%22%3A%22https%3A//playback-mms.spl.org%22%2C%22MMSCache%22%3A%22https%3A//playback-mmscache.spl.org%22%2C%22AUTH%22%3A%22https%3A//playback-api.spl.org%22%2C%22NOTIFY_URL%22%3A%22https%3A//playback-api.spl.org%22%2C%22appID%22%3A%2259456a226f2b713df2de1de5a4873f41e441eaeb%22%2C%22jsfsURL%22%3A%22https%3A//playback-jsfs.spl.org%22%2C%22logURL%22%3A%22https%3A//playback-log.spl.org%22%2C%22host%22%3A%22https%3A//playback.spl.org%22%2C%22mdURL%22%3A%22https%3A//raw.githubusercontent.com/therabble/seattle-public-library-client/master/content%22%2C%22collection%22%3A%22org.spl.playback%22%2C%22name%22%3A%22musicat%22%2C%22version%22%3A%220.0.1+4a72e48e%22%7D%2C%22exportApplicationGlobal%22%3Afalse%2C%22sassOptions%22%3A%7B%22includePaths%22%3A%5B%22bower_components/foundation/scss%22%5D%7D%7D" />

    <link rel="stylesheet" href="assets/vendor-2b37bdb68ba9e2b74489e0c1c6c20196.css" integrity="sha256-lLrr0ZGvgyWsapHcnM/sf67Nd1tAh91i8J7TqRh4vtw= sha512-sGhXsBfpxgEUkHroAVeAf7SzDrg0CyKw1EHm9FhW7poxI5v7HNakG4dakuNpfL18KC01gMg97xetke5VYvZZAA==" >
    <link rel="stylesheet" href="assets/musicat-7cc5733f8664bb63ffec69bd4126ed0d.css" integrity="sha256-28i9G3LI2PqUaJkcgXXfjeSBP1DQU3CwljPNRe6HxmY= sha512-VdG6teRDdyuhxOp0am5nRpjmKXMM4MKY4QkznSIeRHiOtM9udzon+v8BXBV1jiwpCPF+gukOncT8E31MrnI88A==" >
    <link rel="icon" href="assets/favicon-11f1febb2c492430ea2a1261b21866e8.png">

    

  </head>
  <body>
    

    <div class='row loader no-ember'>
      <div class="spinner-wrapper">
        <div class="spinner">
          <img src="/assets/logo_on_white_header-ca3529625a9e99232a6f432cc211c214.png" alt="" width="250" height="89" style="text-align:center;margin-bottom:1rem;">
          <div class="rect1"></div>
          <div class="rect2"></div>
          <div class="rect3"></div>
          <div class="rect4"></div>
          <div class="rect5"></div>
          <div class="rect6"></div>
          <div class="rect7"></div>
          <div class="rect8"></div>
          <div class="rect9"></div>
          <div class="rect10"></div>
        </div>
      </div>
    </div>

    <script src="assets/vendor-00ee53159dd0ea2fa663f8087249c4b5.js" integrity="sha256-zCOnyatQAOmOH4q7gdO6yrLc7NQBFL79511D107kwik= sha512-vyuKJYxx6ShngaOiZ9pIIVoDMfmVZHJSOhpHrh3wsAg8x37Vd6BIp3ke+hEI0zy2fhavCAWI07HG3MxIFlArUA==" ></script>
    <script src="assets/musicat-ef3c6943da3956e7126470cf91f96ddb.js" integrity="sha256-ZgRZweSmrows/fWkk0eg3VC1CXccWHvRqsvl5Z/uTOc= sha512-iMsh701jmoHxxtmrq9UnbJFDPmjOsjl2fYGWa5ZxHUPyNdeHoVtt9W6mImrXiI28r4hLhe1N9P4fN1bqOJn1Pg==" ></script>

    

    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '', 'auto');
      ga('send', 'pageview');
    </script>    

  </body>
</html>

**Comment by kellyhiser** [comment]
based on this feedback, Preston thinks this may be some issue in how security for the site works. Investigating...

**Comment by kellyhiser** [comment]
Issue moved to [therabble/musicat-stem #77](https://github.com/therabble/musicat-stem/issues/77) via [**ZenHub**](https://www.zenhub.com/)
