### ISSUE TITLE
Admin account UX for librarians to create other library admins and jurors

### ISSUE THREAD

**Issue by lahollen** [therabble/org.spl.playback#19]
Create user accounts for jurors to access interface.

**Comment by lahollen** [comment]
@andrewharbison Send names and emails of jurors to me via email.

**Comment by lahollen** [comment]
@prestonaustin Juror names and emails to create accounts are located in shared SPL Google Drive in Metadata & Authentication folder (not linking here for privacy reasons).

**Comment by lahollen** [comment]
Tied to #50. Not critical to going live on submissions.

**Comment by lahollen** [comment]
Admin user account needed for Kate Sellers (formerly #42)

**Comment by lahollen** [comment]
Juror accounts & admin user accounts have all been created. Creating the UX can be pushed back to post-launch.

**Comment by kellyhiser** [comment]
#23 will be fulfilled by this, as librarians can sign in to juror accounts and populate queues.

**Comment by kellyhiser** [comment]
Issue moved to [therabble/musicat-stem #89](https://github.com/therabble/musicat-stem/issues/89) via [**ZenHub**](https://www.zenhub.com/)
