### ISSUE TITLE
Add new playlist feature

### ISSUE THREAD

**Issue by lahollen** [therabble/org.spl.playback#21]
Add new feature for admins or VIP users to create recommended playlists for promotion on the site.

**Comment by lahollen** [comment]
This is a desired feature that could be tied to launch but for now tied to "post launch" as not critical. @kellyhiser - review timeline for this and update.

**Comment by kellyhiser** [comment]
Issue moved to [therabble/musicat-stem #88](https://github.com/therabble/musicat-stem/issues/88) via [**ZenHub**](https://www.zenhub.com/)
