### ISSUE TITLE
Future desired feature: Admin capabilities to publish artist-created tags to main site

### ISSUE THREAD

**Issue by lahollen** [therabble/org.spl.playback#25]
Under consideration for this launch or next round: new feature that would allow admin librarian to publish tags submitted by artists to the main site.

**Comment by kellyhiser** [comment]
We need to review what tags were created during the first submissions round to determine viability of this.

**Comment by kellyhiser** [comment]
Issue moved to [therabble/musicat-stem #85](https://github.com/therabble/musicat-stem/issues/85) via [**ZenHub**](https://www.zenhub.com/)
