### ISSUE TITLE
Decisions re: collecting W-9s thru MUSICat

### ISSUE THREAD

**Issue by lahollen** [therabble/org.spl.playback#28]
1. Is there an IRS policy/precedent for signing W-9s online?
2. If yes, check with SPL finance office for approval.
3. If no to 1 or 2, brainstorm options for how MUSICat could support collecting W-9s if at all.

**Comment by lahollen** [comment]
@kellyhiser re: 1 above: the IRS does allow for electronic submission of W-9s. The system must require same information as paper form, include an electronic signature, and take certain steps to make "reasonably certain" that the form is filled out by the individual and/or an authorized representative. See full IRS instructions for electronic submission here: https://drive.google.com/open?id=0B2JtTtreF1SzUTZBaVVDVGw0LU0 

A Google search also turns up a number of examples online, suggesting lots of precedent.

**Comment by prestonaustin** [comment]
Thanks for this research. So it's clear, we can't commit to this feature in
time for the first public SPL PB submissions round, but I'm happy to look
at trying to get it in there. We wouldn't need it ready until selected
artist invitations to Complete Submission interfaces begin, so it's not
crazy, just not already planned.

**Comment by lahollen** [comment]
@prestonaustin Thanks for clarification. I've attached it to a new milestone ("Artist Invitation Phase Ready" to distinguish from Submissions Ready) but we can move to Post-Launch if needed.

**Comment by lahollen** [comment]
I'm moving this to the post-launch milestone, as we won't be ready to apply this new feature for this round.
