### ISSUE TITLE
Create artist invoice function

### ISSUE THREAD

**Issue by lahollen** [therabble/org.spl.playback#29]
Create function to allow MUSICat to issue invoices to handle payment of artists. Invoice will be from the artist to SPL, and the system will populate fields in the document (a la license).
- [ ] Create invoice template for system. @andrewharbison you'll want to work with your Finance Dept. to create this document.
- [ ] Add invoice function to current admin tools.

**Comment by lahollen** [comment]
Moving to post-launch milestone with #28.

**Comment by kellyhiser** [comment]
closing for now. interest seems low in this feature.
