### ISSUE TITLE
Set up and test MUSICat logging/reporting functions

### ISSUE THREAD

**Issue by lahollen** [therabble/org.spl.playback#79]
The SPB reporting deliverable includes exports of usage data from logs and exports of data from publishing stages. 

Data exports from publishing stages:
- [x] From Jury: All information including notes into CSV files from all pending submissions. **NB this is priority for week of 12/5**
- [x] From Complete Submission: all information (excluding tracks and images) including voluntary demographic information, interest in performing at shows, etc. Ideally, this exports all completed submissions for current round. 
- [ ] Fix honorarium report: Submitter's name, Artist Name, Album Title, Street Address, SSN, phone number, date/time license was signed. 

Logging. Seattle's specific requests are:
- [ ] Number of unique visitors to PlayBack homepage  (covered by GA?)
- [ ] Number of logins
- [ ] Number of album downloads, total and per album and per track
- [ ] Number of album streams, total and per album and per track
- [ ] Number of click-throughs to Artist website, social media, etc

**Comment by kellyhiser** [comment]
July 19: I just tested the "honorarium report" and it's not grabbing data (it spits out a CSV file with the proper fields (date signed, name, etc.) but no data.

**Comment by prestonaustin** [comment]
note to myself: check it sends the right collection heading

**Comment by kellyhiser** [comment]
see what you can pull out of logging since we lost GA data because of bug, see #120

**Comment by kellyhiser** [comment]
Honorarium report: make sure it includes all of contact information for folks including mailing address

**Comment by kellyhiser** [comment]
closing this. see https://github.com/therabble/musicat-stem/issues/82 instead.
